# Generated by Django 4.2.30 on 2026-08-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("distance_km", models.DecimalField(decimal_places=1, max_digits=5)),
                (
                    "elevation_gain",
                    models.IntegerField(default=0, help_text="metres of ascent"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("hard", "Hard"),
                            ("expert", "Expert"),
                        ],
                        default="easy",
                        max_length=10,
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
                ("added", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["distance_km"],
            },
        ),
    ]
